name: Download and process

on: 
  workflow_dispatch:
    inputs:
      colId:
        description: 'Collection ID'     
        required: true
        default: '118102'


jobs:
  build_pages:
    name: Download METS files from Transkribus and convert them to TEIs
    runs-on: ubuntu-latest
    env:
      ANT_OPTS: -Xmx5g
      TR_USER: ${{ secrets.TR_USER }}
      TR_PW: ${{ secrets.TR_PW}}
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v3
    - name: Install Saxon and Ant
      run: |
        mkdir -p mets
        mkdir -p tei
        apt-get update && apt-get install openjdk-11-jre-headless -y --no-install-recommend
        pip install -r requirements.txt
        wget https://sourceforge.net/projects/saxon/files/Saxon-HE/9.9/SaxonHE9-9-1-7J.zip/download && unzip download -d saxon && rm -rf download
        git clone --depth=1 --branch skurzinz-patch-1 --single-branch https://github.com/skurzinz/page2tei.git
    - name: Download METS Files
      run: |
        python ./scripts/fetch_mets.py
    - name: Move METS Files
      run: |
        python ./scripts/move_mets.py
    - name: Transform to TEI
      run: |
        ./transform.sh
    - name: Upconvert
      run: python scripts/create_templates.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Exported and Transformed EMT-Transkribus Collections